# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: On Code, and Other Things
email: talonx at gmail dot com
description: >-
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: talonx
github_username:  talonx

# Build settings
#theme: minima
#theme: beautiful-jekyll-theme
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

#header_pages:
#  - feed.markdown
#  - about.markdown
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: /posts/:year/:month/:day/:title/

#Beautiful Jekyll specific settings
author: Hrishikesh Barua
navbar-links:
  About: about
  RSS: https://feeds.feedburner.com/deepinspace/tech
  Newsletter: https://techops.substack.com/

social-network-links:
  email: "talonx@gmail.com"
  rss: false
  twitter: talonx
  linkedin: hrishikeshbarua
  github: talonx

rss-description: Hrishikesh Barua's tech blog
share-links-active:
  twitter: true
  linkedin: true

feed_show_tags: true
feed_show_excerpt: false
post_search: true

commentbox: "5637229426769920-proj"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

paginate: 8
#paginate_path: posts/:num

# End Beautiful Jekyll

##SEO plugin
twitter:
  username: talonx
  card: summary

#Minima
#social:
#  name: Hrishikesh Barua
#  links:
#    - https://twitter.com/talonx
#    - https://www.linkedin.com/in/hrishikeshbarua
#    - https://github.com/talonx

gtag: G-CRKY08L42Q